### ISSUE TITLE
Implement Defense Technique for BADCODE Method

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDAuditor#1]
**Tasks**

- [ ] Implement the defense technique mentioned in BADCODE Method - paper [Backdooring Neural Code Search](https://arxiv.org/pdf/2305.17506.pdf)
- [ ] Get the sample poisoned data from SEEDPoisoner for BADCODE method.
- [ ] Include above data in your test folder as sample input data for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to those issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file structure information.

**Comment by nitesh31mishra** [comment]
d2f67e5171425db3ca6e1dc79fe52a1bb67679d0 d66b3ceea3bc08602a8cfc194d016e3f2406d25d b3df734034d872756086d0ffad80e31eadb2cc5e 

Final Changes: cede9fe60c5609138394ae900640640ab085bae3

**Comment by maxxbw54** [comment]
hi @nitesh31mishra @pvinoda , is this done already?
