### ISSUE TITLE
Implement Defense Technique for AfraiDoor Method

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDAuditor#3]
**Tasks**

- [ ] Implement the defense technique mentioned in AfraiDoor Method - paper [Stealthy Backdoor Attack for Code Models](https://arxiv.org/pdf/2301.02496.pdf), [Code](https://github.com/yangzhou6666/adversarial-backdoor-for-code-models?tab=readme-ov-file)
- [ ] Get the sample poisoned data from SEEDPoisoner for AfraiDoor method.
- [ ] Include above data in your test folder as sample input data for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to those issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file structure information.
