### ISSUE TITLE
Implement Spectral Signature Method 

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDAuditor#4]
**Tasks**

- [ ] Implement the Spectral Signature defense method mentioned in Backdoor attack paper - [Spectral Signatures in Backdoor Attacks](https://proceedings.neurips.cc/paper/2018/file/280cf18baf4311c92aa5a042336587d3-Paper.pdf)
- [ ] Get the sample poisoned data from SEEDPoisoner if needed.
- [ ] Include above data in your test folder as sample input data for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to those issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file structure information.
